### ISSUE TITLE
Compare diff with tex4tum

### ISSUE THREAD

**Issue by hofbi** [latex4ei/Allgemein#11]
Compare https://github.com/latex4ei/Allgemein/blob/master/README.md with https://github.com/latex4ei/tex4tum/blob/master/_article/sheets.md and check if anything from https://github.com/latex4ei/tex4tum/blob/master/_article/sheets.md is missing in https://github.com/latex4ei/Allgemein/blob/master/README.md. https://github.com/latex4ei/Allgemein/blob/master/README.md should be our groundtruth.

**Comment by dariusptrs** [comment]
All cheat sheets from https://github.com/latex4ei/tex4tum/blob/master/_article/sheets.md are present in https://github.com/latex4ei/Allgemein/blob/master/README.md
