### ISSUE TITLE
New Email Server

### ISSUE THREAD

**Issue by martinzellner** [latex4ei/Allgemein#13]
To fully shut off the old webserver (which I'm sponsoring atm) we need a new (preferably free) way to receive the emails sent to `@latexei` addresses. Any ideas/suggestions @hofbi @dariusptrs ?

**Comment by martinzellner** [comment]
Maybe there is a way to work with the "Fachschaft" for this?

**Comment by dariusptrs** [comment]
> Maybe there is a way to work with the "Fachschaft" for this?

I can look into that.

**Comment by dariusptrs** [comment]
A shared mailbox has been created for our project (latex4ei.stvei@xcit.tum.de). Unfortunately shared mailboxes can only be accessed with an active TUM user account, but we can set up forwarding rules so that Alumni can also receive emails.

The next step would be to use a simple service for automatic email forwarding such as ImprovMX or ForwardEmail.net to send emails to the TUM address.

**Comment by dariusptrs** [comment]
<img width="1117" alt="image" src="https://github.com/user-attachments/assets/67be93ff-f50e-4ca4-adcc-71e3544234dc">

**Comment by martinzellner** [comment]
I can set up the redirection in OVH directly. I'll probably just do that.

**Comment by martinzellner** [comment]
What addresses should we support except for the obvious `info@latex4ei.de`?

**Comment by dariusptrs** [comment]
I don't know. Are there any other ones?

**Comment by dariusptrs** [comment]
What happens to the old emails that have been received on info@latex4ei.de?

**Comment by martinzellner** [comment]
> What addresses should we support except for the obvious `info@latex4ei.de`?

I added forwarding for the following addresses (all to latex4ei.stvei@xcit.tum.de, except mine)

![image](https://github.com/user-attachments/assets/c71ddbcf-484f-4a7a-97f7-1dd07eaabb1b)

**Comment by martinzellner** [comment]
> What happens to the old emails that have been received on [info@latex4ei.de](mailto:info@latex4ei.de)?

I have them all here, happy to share them with you if you want to go through them. I already filtered out all the spam.

**Comment by dariusptrs** [comment]
> > What happens to the old emails that have been received on [info@latex4ei.de](mailto:info@latex4ei.de)?
> 
> 
> 
> I have them all here, happy to share them with you if you want to go through them. I already filtered out all the spam.

Okay, I can do that.

**Comment by martinzellner** [comment]
> > > What happens to the old emails that have been received on [info@latex4ei.de](mailto:info@latex4ei.de)?
> > 
> > 
> > I have them all here, happy to share them with you if you want to go through them. I already filtered out all the spam.
> 
> Okay, I can do that.

Just write me an email or an WhatsApp :)
