### ISSUE TITLE
Gravitationskonstante Falsche Einheit

### ISSUE THREAD

**Issue by victoriafoxgirl** [latex4ei/Allgemein#2]
**Formelsammlung**
Physik 2. Semester

**Fehlerbeschreibung**
Die Gravitationskonstante G hat bei euch die Einheit Nm²/kg, müsste aber entweder Nm²/kg² oder m³/kgs² sein.

**Referenz**
Kapitel I.2 - Konstanten, sowie II.3.1 Kraft

**Comment by hofbi** [comment]
Danke für den Hinweis. Wurde bereits mit https://github.com/latex4ei/Physik/commit/0f59bf9de8b3811fa77b4d1f3432d94710d885ad behoben.
