### ISSUE TITLE
Fehler bei Koordinatentransformation

### ISSUE THREAD

**Issue by ottoblep** [latex4ei/Allgemein#3]
**Formelsammlung**
Analysis 2 Anhang 

**Fehlerbeschreibung**
Bei der Transformation von Kugel zu Zylinderkoordinaten sind sowohl r_z als auch z_z als r_k * sin(theta) angegeben. Das kann nicht sein. 
![Screenshot_20201103_130009](https://user-images.githubusercontent.com/57066925/97982776-8cf3eb00-1dd4-11eb-8672-1d30228238ca.png)
Wenn man Theta als Winkel zur z-Achse definiert muss z_z = r_k * cos_(theta) sein. Auf der Website von der der Anhang geommen wurde (http://www.calc3d.com/help/gcoord.html) ist der Fehler ebenfalls vorhanden.

**Referenz**
https://de.wikipedia.org/wiki/Kugelkoordinaten

**Comment by hofbi** [comment]
Danke für den Hinweis. Ist behoben mit https://github.com/latex4ei/Analysis-2/commit/ad8c50ddc08fdb071b59ec0fab1af1261fa95d04

Die neue Version sollte in ca. 10 Minuten neu hochgeladen sein.
