### ISSUE TITLE
Website Kontaktformular

### ISSUE THREAD

**Issue by Grafrucola** [latex4ei/Allgemein#4]
auf der website spinnt das "Mail Fenster" für feedback scheinbar etwas 
nach dem man auf abschicken drückt steht ewig "Bitte warten..." , es wirkt so als ob nix gesendet wird 

Safari Version 14.0.2 (15610.3.7.1.10, 15610)

**Comment by hofbi** [comment]
@emareg Denke das liegt an der Migration auf den neuen Server. Da hat sich dann auch der Mailserver geändert. Kann du da Martin mal fragen ob er das updaten kann

**Comment by martinzellner** [comment]
The old website was discontinued. We now have a shared mail account under `info@latex4ei.de` that we monitor (thanks @dariusptrs !)
