### ISSUE TITLE
Analysis 2 Formelsammlung 

### ISSUE THREAD

**Issue by Grafrucola** [latex4ei/Allgemein#5]
ich denke in der ANA2 fs (Stand: 3.11.2020) ist ein Fehler 

([pdf](https://github.com/latex4ei/Analysis-2/raw/gh-pages/Analysis-2.pdf) Seite1)
bei der **Ableitungen** von **ln(ax)** 
unter abschnitt **1.1 integrale** in der Tabelle 
die Ableitung müsste "**1/x**" sein _(es steht "a/x" da )_

**Comment by hofbi** [comment]
Danke für den Hinweis. In ca 15 Minuten sollte die neue Version online sein
