### ISSUE TITLE
"Rezeprozität" statt Reziprozität

### ISSUE THREAD

**Issue by davrad3** [latex4ei/Allgemein#6]
Unter Punkt 6 in der Formelsammlung für ST 1. Semester habe ich oben genannten Fehler entdeckt.
Vielen Dank für deine Formelsammlungen!

**Comment by hofbi** [comment]
Behoben mit https://github.com/latex4ei/Schaltungstechnik-1-2/commit/1bcf11c6ffab9b0b7080a5c928d816458409d911
