### ISSUE TITLE
List all sheets from latex4ei.de in the README

### ISSUE THREAD

**Issue by hofbi** [latex4ei/Allgemein#7]
Motivated by https://github.com/latex4ei/Computertechnik/issues/1 and the fact that not everyone can access the website, I thought about managing the website content on GitHub as well.

I created a first draft in https://github.com/latex4ei/Allgemein/blob/master/README.md#formelsammungen, but we would need to add the rest as well. Once this is done, we could update latex4ei.de to point to this repo. Additionally, we could also setup a static page generator, but looking at the many "awesome ..." repos, having a simple markdown could do the job.

@dariusptrs What do you think?

**Comment by dariusptrs** [comment]
Sound good! I can add all the other repos later. 

We could also add the CI status badge to the table and get the date of last commit to show next to it (maybe using a workflow that runs every 24 hours and updates the table).

**Comment by hofbi** [comment]
Great idea with the badge. I think there are some badges that show that automatically without a job that updates them.

**Comment by dariusptrs** [comment]
I added the rest to the markdown file and did some formatting. Whats your opinion on the current looks?

Also, the repositories that do not use gh-actions yet show a `?` as the badge. We would need to update them manually.

**Comment by dariusptrs** [comment]
Found a workaround. Adding a workflow file that doesn't do anything will generate a status badge. Then from time to time we can update the repos to actually show a `passing` badge instead of `no status`.

**Comment by hofbi** [comment]
I like the new style of the readme. Feel free to open a PR once you are happy. Then I can add some last review comments.

Regarding the missing status badge, we could just leave it out or empty. This way, we also have an overview which repo is still missing a CI.
